[build]
builder = "nixpacks"
buildCommand = "NODE_OPTIONS=\"--max-old-space-size=4096\" pnpm build"

[deploy]
startCommand = "cd apps/web && node .next/standalone/server.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure" 