name: Deploy to Coolify

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Test the build with memory limits first
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.2.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Verify build passes with memory constraints
        env:
          NODE_OPTIONS: "--max-old-space-size=2048"
          NEXT_TELEMETRY_DISABLED: 1
        run: pnpm build

      # Now deploy to Coolify if build succeeded
      - name: Deploy to Coolify
        env:
          COOLIFY_URL: ${{ secrets.COOLIFY_URL }}
          COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
          PROJECT_ID: ${{ secrets.COOLIFY_PROJECT_ID }}
        run: |
          # Use Coolify CLI or API to trigger deployment
          curl -X POST "${COOLIFY_URL}/api/v1/deploy/${PROJECT_ID}" \
            -H "Authorization: Bearer ${COOLIFY_TOKEN}" \
            -H "Content-Type: application/json" \
            --data '{"forceRebuild": true}'
